# Generated by Django 5.0.2 on 2024-02-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.CharField(max_length=50, verbose_name='Born date'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
