# Generated by Django 5.0.2 on 2024-02-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_author_born_date_alter_author_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.CharField(max_length=3000),
        ),
    ]
